spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:C:/data/sample
    driverClassName: org.h2.Driver
    username: nmy
    password: nmy

  jpa:
    hibernate:
#      ddl-auto: create   절대 키지말것 키면 DB 다 날라감
