INSERT INTO WORD VALUES(1, '강아지' , 'ANIMAL');
INSERT INTO WORD VALUES(2, '고양이', 'ANIMAL');
INSERT INTO WORD VALUES(3, '코끼리', 'ANIMAL');
INSERT INTO WORD VALUES(4, '기린', 'ANIMAL');
INSERT INTO WORD VALUES(5, '사자', 'ANIMAL');
INSERT INTO WORD VALUES(6, '돌고래', 'ANIMAL');
INSERT INTO WORD VALUES(7, '금붕어', 'ANIMAL');
INSERT INTO WORD VALUES(8, '인간', 'ANIMAL');